# Manuell erstellen mit:
# kubectl create secret generic gitlab-credentials \
#   --namespace=blauweiss \
#   --from-literal=GITLAB_TOKEN="glpat-xxx" \
#   --from-literal=GITLAB_PROJECT_ID="77555895"
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
  namespace: blauweiss
type: Opaque
stringData:
  GITLAB_TOKEN: "REPLACE_ME"
  GITLAB_PROJECT_ID: "77555895"
